"""add Department

Revision ID: 27de19c92381
Revises: fa76f15ec622
Create Date: 2025-03-28 08:55:32.296600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27de19c92381'
down_revision = 'fa76f15ec622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
