"""rename department

Revision ID: c7f2a7bc9e28
Revises: 27de19c92381
Create Date: 2025-03-28 09:00:34.708890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f2a7bc9e28'
down_revision = '27de19c92381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')

    # ### end Alembic commands ###
